name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: enable experimental features
      run: "sudo mkdir -p /etc/docker && echo '{\"experimental\": true}' | sudo tee /etc/docker/daemon.json"
    - name: enable experimental features on client
      run: "mkdir -p ~/.docker && echo '{\"experimental\": \"enabled\"}' | tee ~/.docker/config.json"
    - name: service restart
      run: sudo service docker restart   
    - name: Build the OXID 6.1 Docker image
      run: docker build . --squash --file Dockerfile --build-arg OXID=6.1 --tag keywanghadamioxid/oxid-test:6.1
    - name: Build the OXID 6.2 Docker image
      run: docker build . --squash --file Dockerfile --build-arg OXID=6.2 --tag keywanghadamioxid/oxid-test:6.2
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Publish OXID 6.1 Docker image on Docker Hub
      run: docker push keywanghadamioxid/oxid-test:6.1  
    - name: Publish OXID 6.2 Docker image on Docker Hub
      run: docker push keywanghadamioxid/oxid-test:6.2
      
